favicon: /favicon.ico
rss: true

license:
  name: CC BY-NC-SA 4.0
  url: https://creativecommons.org/licenses/by-nc-sa/4.0/

index_post_count: 5
tag_post_count: 3
read_cpm: 220
old_post_before: 730

paths:
  tags: tags
  series: false

extra_header_links:

features:
  hitokoto: true
  show_url_for_xs: true
  toc: true
  bgtitle: true
  comments: false # Also: edit themes/saas/layout/_custom/comments.ejs

  # Linkback
  #linkbackPostOnly: false
  #webmention: https://webmention.io/example.com/webmention
  #pingback: https://webmention.io/example.com/xmlrpc

# Don't change anything below

node_sass:
  debug: true
  includePaths:
    - node_modules
    - themes/saas/node_modules
